#!/bin/sh

# This file is prevent commits to main!
# This file doesn't do anything unless you write the following commands
# while in the root directory:
#
# git config core.hooksPath githooks
# chmod +x githooks/pre-commit
#
#
#

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi
